spring:
    datasource:
        url: jdbc:mysql://ping-pong.cysyd4nbad9v.ap-northeast-2.rds.amazonaws.com:3306/pingpongdb?autoReconnect=true
        username: admin
        password: hd30727!
        driver-class-name : com.mysql.cj.jdbc.Driver