spring:
    datasource:
        url: jdbc:mysql://ping-pong.cysyd4nbad9v.ap-northeast-2.rds.amazonaws.com:3306/pingpongdb?autoReconnect=true
        username: admin
        password: hd30727!
        driver-class-name : com.mysql.cj.jdbc.Driver
    config:
        activate:
            on-profile: prod
---
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pingpong?autoReconnect=true
        username: root
        password: A1b2c347
        driver-class-name : com.mysql.cj.jdbc.Driver

    config:
        activate:
            on-profile: dev

    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            generate-ddl: true

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        authorization-grant-type: authorization_code
                        client-id: "1f6fddb56b60c6bedd26a879812f0a7c"
                        redirect-uri: "http://localhost:8080/app/users/kakao"
                        scope:
                            - account_email
                        client-authentication-method: POST
                        client-name: Kakao

                    google:
                        client-id: "499200857499-6ij6ualpg0vqmo6ppvkvd1mtqua0j7hp.apps.googleusercontent.com"
                        client-secret: "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"
                        redirect-uri: "http://localhost:8080/login/oauth2/code/google"
                        scope: "https://www.googleapis.com/auth/userinfo.email"

jwt:
    token:
        secret-key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
