spring:
    datasource:
        url: jdbc:mysql://ping-pong.cysyd4nbad9v.ap-northeast-2.rds.amazonaws.com:3306/pingpongdb?autoReconnect=true
        username: admin
        password: hd30727!
        driver-class-name : com.mysql.cj.jdbc.Driver
    config:
        activate:
            on-profile: prod
---
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pingpong?autoReconnect=true
        username: root
        password: A1b2c347
        driver-class-name : com.mysql.cj.jdbc.Driver

    config:
        activate:
            on-profile: dev

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        authorization-grant-type: authorization_code
                        client-id: "1f6fddb56b60c6bedd26a879812f0a7c"
                        redirect-uri: "http://localhost:8080/app/users/kakao"
                        scope:
                            - account_email
                        client-authentication-method: POST
                        client-name: Kakao


