spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pingpong?autoReconnect=true
    username: root
    password: A1b2c347
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: "1f6fddb56b60c6bedd26a879812f0a7c"
            redirect-uri: "http://localhost:8080/app/users/kakao"
            scope:
              - account_email
            client-authentication-method: POST
            client-name: Kakao

          google:
            client-id : "499200857499-6ij6ualpg0vqmo6ppvkvd1mtqua0j7hp.apps.googleusercontent.com"
            client-secret : "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"
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope : "https://www.googleapis.com/auth/userinfo.email"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secret-key: Q4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4Hsajlshjdfahlskjfhalsjfdkdahslfjkafhsldjfhldajfhksdahlf
    expire-length: 86400

properties:
  hibernate:
    globally_quoted_identifiers: true